### ISSUE TITLE
Separate code with backwards compatibility guarantees

### ISSUE THREAD

**Issue by seanjreilly** [EqualExperts/opslogger#4]
We're still pre-1.0, so everything can change at this point, but a strategy of minimising the amount of code that needs to be backwards compatible seems like a good idea. This is currently done by having everything in one package, but making most classes package scope, with only a few classes and interfaces public.

A nicer way of separating API from implementation would be nice -- even if it's just separate source tress so that it's obvious what is API and what isn't.

**Comment by seanjreilly** [comment]
@ravn: I've pushed a branch ("issue-4") that splits the api classes from the implementation classes. The api classes stay where they were, and the implementation classes are moved to a sub package ("impl"), and are now public. I was hoping to get your feedback before merging this change to master.

What do you think?

**Comment by ravn** [comment]
Hi.

I have been out of the loop for a bit.  Sorry for not responding to this in time.  Do you still need my feedback?

**Comment by seanjreilly** [comment]
@ravn No problem, and likewise, sorry for *my* delay in responding. With regards to the issue, I've already merged and released the changes, but I definitely welcome your feedback nonetheless. In my opinion it would be very easy to try a different solution, and by definition this won't affect backwards compatibility. So please, feel free to take a look!

**Comment by ravn** [comment]
I like the change.  It is very clear from the structure that LogMessage, OpsLogger and OpsLoggerFactory are public and the rest is impl.   I am not sure if I like that the "async" feature introduces if-statements all over the place.  I think the slf4j approach is better - the overall behaviour is determined from the backend chosen and not from boolean setters.  This would also allow for separating the API into an individual artifact.
